// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.NameFormatter
{
    [NameFormatterResourceType("name-formatter:index:Module")]
    public partial class Module : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The formatted full name
        /// </summary>
        [Output("whole_name")]
        public Output<object?> Whole_name { get; private set; } = null!;


        /// <summary>
        /// Create a Module resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Module(string name, ModuleArgs args, CustomResourceOptions? options = null)
            : base("name-formatter:index:Module", name, args ?? new ModuleArgs(), MakeResourceOptions(options, ""), Utilities.PackageParameterization())
        {
        }

        private Module(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("name-formatter:index:Module", name, null, MakeResourceOptions(options, id), Utilities.PackageParameterization())
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Module resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Module Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Module(name, id, options);
        }
    }

    public sealed class ModuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The first name of the person
        /// </summary>
        [Input("first_name", required: true)]
        public Input<string> First_name { get; set; } = null!;

        /// <summary>
        /// The last name of the person
        /// </summary>
        [Input("last_name", required: true)]
        public Input<string> Last_name { get; set; } = null!;

        public ModuleArgs()
        {
        }
        public static new ModuleArgs Empty => new ModuleArgs();
    }
}
